"""
AIthusiast Seed Data — 50+ curated AI tools + 12 editorial articles + 6 curated stacks.
"""

# ──────────────────────────────────────────────────────────────────
# AI Tools  (50+)
# Categories: prompting, image-generation, video, coding, design,
# productivity, research, voice, 3d, automation
# ──────────────────────────────────────────────────────────────────
TOOLS_SEED = [
    # PROMPTING / LLMs
    {
        "id": "chatgpt", "name": "ChatGPT", "tagline": "The original conversational AI.",
        "description": "OpenAI's flagship conversational assistant for writing, brainstorming, analysis and code.",
        "category": "prompting",
        "strengths": ["General reasoning", "Versatile writing", "Plugins & GPTs"],
        "tags": ["llm", "chat", "openai", "general"], "pricing": "freemium",
        "url": "https://chatgpt.com", "logo": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
        "accent": "#10A37F", "trending": True, "featured": True,
        "rank": 1, "weekly_growth": "+8%", "popularity": 98,
    },
    {
        "id": "claude", "name": "Claude", "tagline": "Anthropic's nuanced, long-context AI.",
        "description": "Excels at long documents, careful writing, code review and complex reasoning with 200K context.",
        "category": "prompting",
        "strengths": ["Long-context", "Nuanced writing", "Code understanding"],
        "tags": ["llm", "anthropic", "writing", "code"], "pricing": "freemium",
        "url": "https://claude.ai", "logo": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
        "accent": "#D97757", "trending": True, "featured": True,
        "rank": 2, "weekly_growth": "+22%", "popularity": 94,
    },
    {
        "id": "gemini", "name": "Gemini", "tagline": "Google's multimodal AI.",
        "description": "Multimodal AI integrated across Google Workspace, with strong reasoning and free generous tier.",
        "category": "prompting",
        "strengths": ["Multimodal", "Workspace integration", "Free tier"],
        "tags": ["llm", "google", "multimodal"], "pricing": "freemium",
        "url": "https://gemini.google.com", "logo": "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80",
        "accent": "#4285F4", "trending": True, "featured": False,
        "rank": 3, "weekly_growth": "+31%", "popularity": 91,
    },
    {
        "id": "grok", "name": "Grok", "tagline": "xAI's witty real-time assistant.",
        "description": "Real-time information from X with a personality — fast, irreverent, and integrated everywhere.",
        "category": "prompting",
        "strengths": ["Real-time", "Personality", "X integration"],
        "tags": ["llm", "xai", "realtime"], "pricing": "paid",
        "url": "https://grok.com", "logo": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80",
        "accent": "#A855F7",
    },
    {
        "id": "mistral", "name": "Mistral", "tagline": "European open-source LLMs.",
        "description": "Open-weight models from Paris with strong code and reasoning performance.",
        "category": "prompting",
        "strengths": ["Open-source", "European", "Code-focused"],
        "tags": ["llm", "open-source", "europe"], "pricing": "freemium",
        "url": "https://mistral.ai", "logo": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
        "accent": "#FF6B35",
    },
    {
        "id": "llama", "name": "Llama", "tagline": "Meta's open-weight foundation.",
        "description": "Meta's open-weight model family — runnable locally, fine-tunable, the backbone of countless open AI tools.",
        "category": "prompting",
        "strengths": ["Open-weight", "Self-hostable", "Customizable"],
        "tags": ["llm", "open-source", "meta", "local"], "pricing": "free",
        "url": "https://llama.meta.com", "logo": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
        "accent": "#0064E0",
    },
    {
        "id": "deepseek", "name": "DeepSeek", "tagline": "Frontier open reasoning models.",
        "description": "Open-source reasoning models rivalling closed frontier labs at a fraction of the cost.",
        "category": "prompting",
        "strengths": ["Reasoning", "Open-source", "Cost-efficient"],
        "tags": ["llm", "open-source", "reasoning"], "pricing": "freemium",
        "url": "https://deepseek.com", "logo": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
        "accent": "#7C3AED",
    },

    # IMAGE GENERATION
    {
        "id": "midjourney", "name": "Midjourney", "tagline": "Cinematic AI imagery.",
        "description": "The benchmark for artistic, painterly, cinematic AI imagery. Discord-native with a polished web app.",
        "category": "image-generation",
        "strengths": ["Cinematic style", "Artistic quality", "Strong community"],
        "tags": ["image", "art", "cinematic"], "pricing": "paid",
        "url": "https://midjourney.com", "logo": "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&q=80",
        "accent": "#A855F7", "trending": True, "featured": True,
        "rank": 5, "weekly_growth": "+12%", "popularity": 88,
    },
    {
        "id": "dalle3", "name": "DALL·E 3", "tagline": "OpenAI's image powerhouse.",
        "description": "Excellent prompt adherence and crisp text rendering, integrated into ChatGPT.",
        "category": "image-generation",
        "strengths": ["Prompt adherence", "Text in image", "Easy via ChatGPT"],
        "tags": ["image", "openai"], "pricing": "paid",
        "url": "https://openai.com/dall-e-3", "logo": "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&q=80",
        "accent": "#10A37F",
    },
    {
        "id": "flux", "name": "Flux", "tagline": "Open-source photorealism.",
        "description": "Black Forest Labs' open model with stunning photorealism and runnable on consumer hardware.",
        "category": "image-generation",
        "strengths": ["Photorealistic", "Open-source", "Self-hostable"],
        "tags": ["image", "open-source", "photorealism"], "pricing": "freemium",
        "url": "https://blackforestlabs.ai", "logo": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=800&q=80",
        "accent": "#000000", "trending": True,
        "rank": 9, "weekly_growth": "+44%", "popularity": 78,
    },
    {
        "id": "sdxl", "name": "Stable Diffusion XL", "tagline": "The open-source classic.",
        "description": "Stability AI's open image model — endless community fine-tunes, LoRAs and workflows.",
        "category": "image-generation",
        "strengths": ["Open-source", "Customizable", "Community LoRAs"],
        "tags": ["image", "open-source", "stable-diffusion"], "pricing": "free",
        "url": "https://stability.ai", "logo": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80",
        "accent": "#FF6B6B",
    },
    {
        "id": "ideogram", "name": "Ideogram", "tagline": "Typography that actually works.",
        "description": "Best-in-class for text rendering in images — posters, logos, ads, and graphics with real type.",
        "category": "image-generation",
        "strengths": ["Typography", "Logos & ads", "Crisp text"],
        "tags": ["image", "typography", "design"], "pricing": "freemium",
        "url": "https://ideogram.ai", "logo": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
        "accent": "#FF4ECD",
    },
    {
        "id": "leonardo", "name": "Leonardo AI", "tagline": "Game-ready AI art.",
        "description": "Tuned for game assets, concept art, and consistent character generation.",
        "category": "image-generation",
        "strengths": ["Game assets", "Concept art", "Character consistency"],
        "tags": ["image", "game", "concept-art"], "pricing": "freemium",
        "url": "https://leonardo.ai", "logo": "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80",
        "accent": "#F4D03F",
    },
    {
        "id": "krea", "name": "Krea", "tagline": "Real-time AI canvas.",
        "description": "Real-time generation, enhancement and creative editing — feels like a futuristic Photoshop.",
        "category": "image-generation",
        "strengths": ["Real-time", "Creative editing", "Enhance & upscale"],
        "tags": ["image", "realtime", "editing"], "pricing": "freemium",
        "url": "https://krea.ai", "logo": "https://images.unsplash.com/photo-1641531027302-c08fee2f97ee?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1641531027302-c08fee2f97ee?w=800&q=80",
        "accent": "#7C3AED",
    },
    {
        "id": "recraft", "name": "Recraft", "tagline": "Brand-grade vector & raster AI.",
        "description": "Generate brand-consistent illustrations, icons, and vectors with style controls.",
        "category": "image-generation",
        "strengths": ["Brand consistency", "Vectors", "Icons & illustrations"],
        "tags": ["image", "vector", "brand"], "pricing": "freemium",
        "url": "https://recraft.ai", "logo": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&q=80",
        "accent": "#FF6B6B",
    },

    # VIDEO
    {
        "id": "runway", "name": "Runway", "tagline": "Cinematic AI video.",
        "description": "Gen-3 is the most polished AI video model — used in real productions for shots and VFX.",
        "category": "video",
        "strengths": ["Cinematic motion", "VFX-ready", "Pro workflows"],
        "tags": ["video", "filmmaking", "vfx"], "pricing": "paid",
        "url": "https://runwayml.com", "logo": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
        "accent": "#FFFFFF", "trending": True, "featured": True,
        "rank": 7, "weekly_growth": "+18%", "popularity": 85,
    },
    {
        "id": "sora", "name": "Sora", "tagline": "OpenAI's text-to-video.",
        "description": "Realistic minute-long scenes with strong physics and continuity from a single prompt.",
        "category": "video",
        "strengths": ["Realistic scenes", "Long-form", "Physics"],
        "tags": ["video", "openai"], "pricing": "paid",
        "url": "https://openai.com/sora", "logo": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&q=80",
        "accent": "#10A37F", "trending": True,
        "rank": 8, "weekly_growth": "+52%", "popularity": 82,
    },
    {
        "id": "kling", "name": "Kling", "tagline": "Stunning open video frontier.",
        "description": "Chinese-built model producing some of the most realistic AI video shots available today.",
        "category": "video",
        "strengths": ["Realistic motion", "Affordable", "Camera moves"],
        "tags": ["video", "realistic"], "pricing": "freemium",
        "url": "https://klingai.com", "logo": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80",
        "accent": "#FF4ECD",
    },
    {
        "id": "veo", "name": "Google Veo", "tagline": "Google's cinematic video AI.",
        "description": "High-fidelity, 1080p text-to-video with strong cinematography understanding.",
        "category": "video",
        "strengths": ["1080p", "Cinematography", "Google ecosystem"],
        "tags": ["video", "google"], "pricing": "paid",
        "url": "https://deepmind.google/technologies/veo", "logo": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=800&q=80",
        "accent": "#4285F4",
    },
    {
        "id": "pika", "name": "Pika", "tagline": "Playful video generation.",
        "description": "Fun, fast, prompt-driven video clips — ideal for social, memes and motion ideation.",
        "category": "video",
        "strengths": ["Fast", "Playful", "Social-ready"],
        "tags": ["video", "social"], "pricing": "freemium",
        "url": "https://pika.art", "logo": "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80",
        "accent": "#FF6B6B",
    },
    {
        "id": "heygen", "name": "HeyGen", "tagline": "AI avatars that look real.",
        "description": "Photorealistic AI avatars for marketing, training and localization videos in 175+ languages.",
        "category": "video",
        "strengths": ["Realistic avatars", "Multilingual", "Lip-sync"],
        "tags": ["video", "avatars", "marketing"], "pricing": "freemium",
        "url": "https://heygen.com", "logo": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80",
        "accent": "#7C3AED",
    },

    # CODING
    {
        "id": "github-copilot", "name": "GitHub Copilot", "tagline": "Your AI pair programmer.",
        "description": "Industry-standard IDE assistant powered by OpenAI. Inline suggestions, chat and agents.",
        "category": "coding",
        "strengths": ["IDE integration", "Inline completion", "Enterprise-ready"],
        "tags": ["code", "ide", "github"], "pricing": "paid",
        "url": "https://github.com/features/copilot", "logo": "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80",
        "accent": "#FFFFFF", "trending": True, "featured": True,
        "rank": 6, "weekly_growth": "+15%", "popularity": 87,
    },
    {
        "id": "cursor", "name": "Cursor", "tagline": "AI-first code editor.",
        "description": "VS Code reimagined for AI: codebase-aware chat, agents, and lightning-fast multi-file edits.",
        "category": "coding",
        "strengths": ["Codebase-aware", "Agents", "Multi-file edits"],
        "tags": ["code", "ide", "agent"], "pricing": "freemium",
        "url": "https://cursor.com", "logo": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
        "accent": "#000000", "trending": True, "featured": True,
        "rank": 4, "weekly_growth": "+38%", "popularity": 90,
    },
    {
        "id": "windsurf", "name": "Windsurf", "tagline": "Agentic IDE by Codeium.",
        "description": "An agentic flow-state IDE that plans, edits, runs and iterates with you.",
        "category": "coding",
        "strengths": ["Agentic flows", "Fast", "Smart context"],
        "tags": ["code", "ide", "agent"], "pricing": "freemium",
        "url": "https://codeium.com/windsurf", "logo": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        "accent": "#06B6D4",
    },
    {
        "id": "v0", "name": "v0 by Vercel", "tagline": "UI generation, perfected.",
        "description": "Generate production-quality React + Tailwind components from prompts and screenshots.",
        "category": "coding",
        "strengths": ["React + Tailwind", "Production-ready output", "Shadcn-aware"],
        "tags": ["code", "ui", "react"], "pricing": "freemium",
        "url": "https://v0.dev", "logo": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80",
        "accent": "#FFFFFF", "featured": True,
    },
    {
        "id": "bolt", "name": "Bolt.new", "tagline": "AI full-stack in the browser.",
        "description": "Prompt a full-stack app and run it instantly in a browser-based dev environment.",
        "category": "coding",
        "strengths": ["Browser dev env", "Full-stack", "Instant deploy"],
        "tags": ["code", "fullstack", "no-code"], "pricing": "freemium",
        "url": "https://bolt.new", "logo": "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=800&q=80",
        "accent": "#FBBF24",
    },
    {
        "id": "replit-agent", "name": "Replit Agent", "tagline": "Ship apps from a prompt.",
        "description": "An autonomous agent that builds, deploys and iterates apps inside Replit's cloud IDE.",
        "category": "coding",
        "strengths": ["Cloud IDE", "Agent autonomy", "One-click deploy"],
        "tags": ["code", "agent", "fullstack"], "pricing": "freemium",
        "url": "https://replit.com", "logo": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80",
        "accent": "#F26207",
    },
    {
        "id": "tabnine", "name": "Tabnine", "tagline": "Private code AI.",
        "description": "Enterprise-grade code assistant with on-prem and air-gapped deployment options.",
        "category": "coding",
        "strengths": ["Privacy", "Enterprise", "Self-host"],
        "tags": ["code", "enterprise", "privacy"], "pricing": "freemium",
        "url": "https://tabnine.com", "logo": "https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=800&q=80",
        "accent": "#7C3AED",
    },

    # DESIGN
    {
        "id": "figma-ai", "name": "Figma AI", "tagline": "AI inside the design tool you love.",
        "description": "Native AI features: visual search, generative design assist and content fill.",
        "category": "design",
        "strengths": ["Native to Figma", "Collaboration", "Visual search"],
        "tags": ["design", "ui", "ux"], "pricing": "freemium",
        "url": "https://figma.com", "logo": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
        "accent": "#F24E1E", "featured": True,
    },
    {
        "id": "uizard", "name": "Uizard", "tagline": "Sketch → design.",
        "description": "Turn sketches and screenshots into editable UI designs, fast.",
        "category": "design",
        "strengths": ["Sketch to UI", "Wireframing", "Brand themes"],
        "tags": ["design", "ui", "wireframe"], "pricing": "freemium",
        "url": "https://uizard.io", "logo": "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=800&q=80",
        "accent": "#7C3AED",
    },
    {
        "id": "galileo", "name": "Galileo AI", "tagline": "Production-quality UI from text.",
        "description": "Generate high-fidelity UI designs from a single sentence, ready to refine in Figma.",
        "category": "design",
        "strengths": ["High-fidelity output", "Figma-ready", "Fast ideation"],
        "tags": ["design", "ui", "figma"], "pricing": "paid",
        "url": "https://usegalileo.ai", "logo": "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800&q=80",
        "accent": "#A855F7",
    },
    {
        "id": "framer-ai", "name": "Framer AI", "tagline": "Publish a site by typing.",
        "description": "Prompt to publish: an AI-powered design tool that ships polished marketing sites.",
        "category": "design",
        "strengths": ["Prompt to site", "Polished output", "CMS included"],
        "tags": ["design", "website", "no-code"], "pricing": "freemium",
        "url": "https://framer.com", "logo": "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80",
        "accent": "#0055FF",
    },
    {
        "id": "magnific", "name": "Magnific", "tagline": "Insane AI upscaling.",
        "description": "Hallucinate details into low-res images for film, art and product photography.",
        "category": "design",
        "strengths": ["Upscaling", "Detail synthesis", "Print-ready"],
        "tags": ["design", "upscale", "image"], "pricing": "paid",
        "url": "https://magnific.ai", "logo": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
        "accent": "#A855F7",
    },

    # PRODUCTIVITY
    {
        "id": "notion-ai", "name": "Notion AI", "tagline": "AI inside your workspace.",
        "description": "Summaries, writing assistance and Q&A across all your Notion docs and databases.",
        "category": "productivity",
        "strengths": ["Workspace context", "Summarize & write", "Q&A across docs"],
        "tags": ["productivity", "notes", "workspace"], "pricing": "paid",
        "url": "https://notion.so/product/ai", "logo": "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
        "accent": "#FFFFFF", "trending": True,
    },
    {
        "id": "gamma", "name": "Gamma", "tagline": "Decks from a prompt.",
        "description": "Beautiful presentations, docs and webpages generated and editable in seconds.",
        "category": "productivity",
        "strengths": ["Fast slides", "Modern design", "Editable output"],
        "tags": ["productivity", "slides", "presentations"], "pricing": "freemium",
        "url": "https://gamma.app", "logo": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80",
        "accent": "#A855F7", "featured": True,
    },
    {
        "id": "tome", "name": "Tome", "tagline": "Sales storytelling AI.",
        "description": "Sales-focused decks and one-pagers tailored to each prospect via AI research.",
        "category": "productivity",
        "strengths": ["Sales personalization", "Auto research", "Storytelling"],
        "tags": ["productivity", "sales", "presentations"], "pricing": "paid",
        "url": "https://tome.app", "logo": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        "accent": "#7C3AED",
    },
    {
        "id": "mem", "name": "Mem", "tagline": "Self-organizing notes.",
        "description": "AI-native notes that auto-link, surface and remind \u2014 a second brain that actually works.",
        "category": "productivity",
        "strengths": ["Auto-linking", "Recall", "AI search"],
        "tags": ["productivity", "notes", "knowledge"], "pricing": "freemium",
        "url": "https://mem.ai", "logo": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80",
        "accent": "#06B6D4",
    },
    {
        "id": "superhuman", "name": "Superhuman", "tagline": "Email at the speed of thought.",
        "description": "AI triage, instant replies and split inbox — the fastest inbox you'll use.",
        "category": "productivity",
        "strengths": ["Speed", "AI triage", "Keyboard-first"],
        "tags": ["productivity", "email"], "pricing": "paid",
        "url": "https://superhuman.com", "logo": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80",
        "accent": "#FFFFFF",
    },
    {
        "id": "granola", "name": "Granola", "tagline": "Meeting notes done right.",
        "description": "Listens in the background, augments your notes with AI \u2014 no bot required.",
        "category": "productivity",
        "strengths": ["No meeting bot", "AI augmentation", "Templated outputs"],
        "tags": ["productivity", "meetings", "notes"], "pricing": "freemium",
        "url": "https://granola.ai", "logo": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80",
        "accent": "#A855F7",
    },

    # RESEARCH
    {
        "id": "perplexity", "name": "Perplexity", "tagline": "Answer engine with citations.",
        "description": "Search reimagined: instant cited answers, follow-up threads and real-time web access.",
        "category": "research",
        "strengths": ["Cited answers", "Real-time", "Threaded research"],
        "tags": ["research", "search"], "pricing": "freemium",
        "url": "https://perplexity.ai", "logo": "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=800&q=80",
        "accent": "#20B2AA", "trending": True, "featured": True,
        "rank": 10, "weekly_growth": "+26%", "popularity": 76,
    },
    {
        "id": "elicit", "name": "Elicit", "tagline": "Literature review automated.",
        "description": "Find, summarize and extract data from 200M+ research papers in minutes.",
        "category": "research",
        "strengths": ["Literature review", "Paper extraction", "Academic"],
        "tags": ["research", "academic", "papers"], "pricing": "freemium",
        "url": "https://elicit.com", "logo": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
        "accent": "#10B981",
    },
    {
        "id": "consensus", "name": "Consensus", "tagline": "Evidence from peer-reviewed papers.",
        "description": "Ask any research question and get an evidence-based answer with paper citations.",
        "category": "research",
        "strengths": ["Evidence-based", "Peer-reviewed", "Science search"],
        "tags": ["research", "science"], "pricing": "freemium",
        "url": "https://consensus.app", "logo": "https://images.unsplash.com/photo-1532153975070-2e9ab71f1b14?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1532153975070-2e9ab71f1b14?w=800&q=80",
        "accent": "#7C3AED",
    },

    # VOICE
    {
        "id": "elevenlabs", "name": "ElevenLabs", "tagline": "Most realistic AI voice.",
        "description": "Studio-grade voice generation and cloning in 32+ languages with emotional control.",
        "category": "voice",
        "strengths": ["Realistic voices", "Cloning", "Multilingual"],
        "tags": ["voice", "tts", "audio"], "pricing": "freemium",
        "url": "https://elevenlabs.io", "logo": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80",
        "accent": "#000000", "trending": True, "featured": True,
    },
    {
        "id": "suno", "name": "Suno", "tagline": "AI music from a prompt.",
        "description": "Produce full songs with vocals, instruments and lyrics from a single line.",
        "category": "voice",
        "strengths": ["Full songs", "Vocals", "Lyrics & instruments"],
        "tags": ["voice", "music", "audio"], "pricing": "freemium",
        "url": "https://suno.com", "logo": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
        "accent": "#FF6B6B", "trending": True,
    },
    {
        "id": "udio", "name": "Udio", "tagline": "Studio-quality music AI.",
        "description": "High-fidelity music generation favored by producers for polished, mix-ready output.",
        "category": "voice",
        "strengths": ["High-fidelity", "Producer-grade", "Stems"],
        "tags": ["voice", "music"], "pricing": "freemium",
        "url": "https://udio.com", "logo": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
        "accent": "#A855F7",
    },
    {
        "id": "descript", "name": "Descript", "tagline": "Edit audio like a doc.",
        "description": "Podcast and video editing with AI transcription, overdub voices and studio-quality cleanup.",
        "category": "voice",
        "strengths": ["Doc-style editing", "Overdub", "Studio cleanup"],
        "tags": ["voice", "podcast", "editing"], "pricing": "freemium",
        "url": "https://descript.com", "logo": "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80",
        "accent": "#2D2D2D",
    },

    # 3D
    {
        "id": "luma", "name": "Luma AI", "tagline": "Capture & generate 3D.",
        "description": "Turn videos into 3D NeRF captures or generate new 3D scenes and assets from text.",
        "category": "3d",
        "strengths": ["NeRFs", "3D captures", "Text-to-3D"],
        "tags": ["3d", "nerf", "ar"], "pricing": "freemium",
        "url": "https://lumalabs.ai", "logo": "https://images.unsplash.com/photo-1635776062127-d379bfcba9f8?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1635776062127-d379bfcba9f8?w=800&q=80",
        "accent": "#A855F7", "trending": True,
    },
    {
        "id": "spline", "name": "Spline AI", "tagline": "3D scenes in the browser.",
        "description": "Design real-time 3D experiences with an AI assistant — export to web, AR and games.",
        "category": "3d",
        "strengths": ["Browser-based", "Realtime 3D", "Web export"],
        "tags": ["3d", "web"], "pricing": "freemium",
        "url": "https://spline.design", "logo": "https://images.unsplash.com/photo-1633186710893-43dffd0e5b53?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1633186710893-43dffd0e5b53?w=800&q=80",
        "accent": "#FF6B6B",
    },
    {
        "id": "meshy", "name": "Meshy", "tagline": "Text & image to 3D mesh.",
        "description": "Generate game-ready 3D models with textures and rigging from prompts and references.",
        "category": "3d",
        "strengths": ["Text to 3D", "Game-ready", "Texturing"],
        "tags": ["3d", "game"], "pricing": "freemium",
        "url": "https://meshy.ai", "logo": "https://images.unsplash.com/photo-1614935151651-0bea6508db6b?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1614935151651-0bea6508db6b?w=800&q=80",
        "accent": "#06B6D4",
    },

    # AUTOMATION
    {
        "id": "zapier-ai", "name": "Zapier AI", "tagline": "Automate everything with AI.",
        "description": "Connect 6000+ apps with AI-powered actions \u2014 the easiest way to automate without code.",
        "category": "automation",
        "strengths": ["No-code", "6000+ apps", "AI actions"],
        "tags": ["automation", "workflow"], "pricing": "freemium",
        "url": "https://zapier.com", "logo": "https://images.unsplash.com/photo-1494178270175-e96de2971df9?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1494178270175-e96de2971df9?w=800&q=80",
        "accent": "#FF4F00", "featured": True,
    },
    {
        "id": "make", "name": "Make", "tagline": "Visual automation playground.",
        "description": "Drag-and-drop scenarios connecting apps, AI agents and APIs into powerful flows.",
        "category": "automation",
        "strengths": ["Visual builder", "Complex flows", "Affordable"],
        "tags": ["automation", "workflow", "no-code"], "pricing": "freemium",
        "url": "https://make.com", "logo": "https://images.unsplash.com/photo-1559586007-7fab8ad6cda0?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1559586007-7fab8ad6cda0?w=800&q=80",
        "accent": "#6D00CC",
    },
    {
        "id": "n8n", "name": "n8n", "tagline": "Open-source automation.",
        "description": "Self-hostable, code-friendly workflow automation with native AI nodes.",
        "category": "automation",
        "strengths": ["Open-source", "Self-host", "AI nodes"],
        "tags": ["automation", "open-source", "self-host"], "pricing": "freemium",
        "url": "https://n8n.io", "logo": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
        "accent": "#EA4B71",
    },
    {
        "id": "lindy", "name": "Lindy", "tagline": "Hire an AI employee.",
        "description": "No-code AI agents that handle email, scheduling, sales and operations end-to-end.",
        "category": "automation",
        "strengths": ["AI employees", "End-to-end tasks", "Integrations"],
        "tags": ["automation", "agent", "no-code"], "pricing": "freemium",
        "url": "https://lindy.ai", "logo": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&q=80",
        "accent": "#7C3AED",
    },
    {
        "id": "browse-ai", "name": "Browse AI", "tagline": "Scrape websites without code.",
        "description": "Train a robot to extract structured data from any website on a schedule.",
        "category": "automation",
        "strengths": ["Web scraping", "Scheduling", "No-code"],
        "tags": ["automation", "scraping"], "pricing": "freemium",
        "url": "https://browse.ai", "logo": "https://images.unsplash.com/photo-1551434678-e076c223a692?w=200&q=80",
        "cover": "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80",
        "accent": "#10B981",
    },
]


# ──────────────────────────────────────────────────────────────────
# Articles  (12 premium editorial pieces)
# ──────────────────────────────────────────────────────────────────
def _section(heading, body):
    return {"heading": heading, "body": body}


ARTICLES_SEED = [
    {
        "id": "art-001",
        "slug": "best-ai-for-students-2026",
        "title": "The AI Operating System every student should run in 2026",
        "deck": "Five tools that replace ten apps — built for late-night essays, lecture notes, and exam season.",
        "cover": "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=1200&q=80",
        "category": "research",
        "reading_time": 4,
        "tags": ["students", "stack", "essential"],
        "featured": True,
        "related_tool_ids": ["chatgpt", "perplexity", "notion-ai", "gamma", "claude"],
        "sections": [
            _section("Why a stack beats a single app",
                     "A single AI cannot replace your study workflow — but five carefully chosen ones can. The trick is selecting tools that share data flow, not just features."),
            _section("Capture: Notion AI",
                     "Live notes that auto-summarize lectures, create flashcards and link to citations. Treat it as your second brain — every PDF, every voice memo, every essay draft."),
            _section("Research: Perplexity",
                     "Ditch the open-tab graveyard. Perplexity answers with citations, threads your follow-ups and exports clean references straight to your bibliography."),
            _section("Draft: Claude or ChatGPT",
                     "Claude shines on long, nuanced essays with personality. ChatGPT wins on quick utility tasks. Keep both within one click."),
            _section("Present: Gamma",
                     "When your seminar deck is due in three hours, Gamma turns an outline into a presentation that actually looks designed."),
            _section("The rule of one",
                     "Pick one tool per job and master it. The premium in AI is no longer access — it's taste and routine."),
        ],
    },
    {
        "id": "art-002",
        "slug": "cinematic-ai-image-stack",
        "title": "Building cinematic stills with AI — a director's stack",
        "deck": "Midjourney, Flux and Magnific working in concert: the workflow used by ad-agency post houses.",
        "cover": "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=1200&q=80",
        "category": "image-generation",
        "reading_time": 5,
        "tags": ["cinematic", "image", "workflow"],
        "featured": True,
        "related_tool_ids": ["midjourney", "flux", "magnific", "krea"],
        "sections": [
            _section("Concept: Midjourney v7",
                     "Midjourney still owns the look of cinema. Lean on lens prompts (35mm anamorphic, kodak portra), and let the model bring the soul."),
            _section("Refine: Flux + Krea",
                     "When you need a specific detail — a hand, a logo, an exact face — open-source Flux gives you control, and Krea lets you paint in real time."),
            _section("Upscale: Magnific",
                     "Hallucinated micro-detail is the secret weapon of print and 4K delivery. Magnific renders skin pores and fabric weaves that no other upscaler matches."),
            _section("Direct, don't generate",
                     "Treat the stack like a crew. You're the director — every prompt is a call sheet."),
        ],
    },
    {
        "id": "art-003",
        "slug": "ai-for-industrial-design",
        "title": "Industrial designers are quietly running their own AI render farms",
        "deck": "Concept to clay model in an afternoon: how Luma, Midjourney and Spline rewire the studio.",
        "cover": "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=1200&q=80",
        "category": "3d",
        "reading_time": 4,
        "tags": ["industrial-design", "3d", "render"],
        "related_tool_ids": ["midjourney", "luma", "spline", "flux"],
        "sections": [
            _section("Sketch in light",
                     "Midjourney generates moodboards no human intern could match. Don't ask for products — ask for atmospheres, then bend them toward your category."),
            _section("Capture the world",
                     "Luma turns a 30-second phone walk-around into a 3D scene you can drop into Blender by lunch."),
            _section("Iterate in the browser",
                     "Spline makes physical-feeling prototypes shareable as a URL. Stakeholders can rotate, comment, decide."),
        ],
    },
    {
        "id": "art-004",
        "slug": "ai-for-coding-2026",
        "title": "The new pair programmers — choosing between Copilot, Cursor and Windsurf",
        "deck": "Three philosophies, one job: which AI editor matches the way you actually code?",
        "cover": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80",
        "category": "coding",
        "reading_time": 6,
        "tags": ["coding", "ide", "developers"],
        "featured": True,
        "related_tool_ids": ["github-copilot", "cursor", "windsurf", "v0"],
        "sections": [
            _section("Copilot — the safest default",
                     "If your team lives in VS Code or JetBrains, Copilot stays out of the way and ships fast. Enterprise-ready, calmly powerful."),
            _section("Cursor — for product builders",
                     "Multi-file edits, codebase-aware chat, agents that ship features. The choice when you want AI to take a real seat at the keyboard."),
            _section("Windsurf — flow state",
                     "Codeium's editor blends agentic flows with a quiet UI. Plan, edit, run — without the context-switch."),
            _section("Pick by friction",
                     "The right editor is the one you forget you're using. Try all three for a week. The one you can't go back from wins."),
        ],
    },
    {
        "id": "art-005",
        "slug": "ai-presentations-decks",
        "title": "Slides without the suffering — AI presentation tools that respect taste",
        "deck": "Gamma, Tome and a few quiet upgrades that finally make a deck a joy to build.",
        "cover": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80",
        "category": "productivity",
        "reading_time": 3,
        "tags": ["presentations", "productivity"],
        "related_tool_ids": ["gamma", "tome", "v0"],
        "sections": [
            _section("Outline first",
                     "Write the deck as a doc. Gamma turns headings into slides — your structure stays clean, your typography stays consistent."),
            _section("Tome for sales",
                     "Personalize each pitch automatically. Tome researches the prospect, drafts the narrative, and lets you re-style in one click."),
        ],
    },
    {
        "id": "art-006",
        "slug": "ai-for-productivity",
        "title": "The quiet productivity stack that buys you back an hour a day",
        "deck": "Three tools, zero novelty — proven workflows for inbox, notes and meetings.",
        "cover": "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=1200&q=80",
        "category": "productivity",
        "reading_time": 4,
        "tags": ["productivity", "workflow"],
        "related_tool_ids": ["superhuman", "notion-ai", "granola", "mem"],
        "sections": [
            _section("Inbox: Superhuman",
                     "AI triage and instant replies. Keyboard-first. You'll never miss zero again."),
            _section("Notes: Notion AI or Mem",
                     "Notion if you live in a team workspace. Mem if you want a personal second brain that organizes itself."),
            _section("Meetings: Granola",
                     "No bot in the meeting. Granola listens in the background, then drafts notes that sound like you wrote them."),
        ],
    },
    {
        "id": "art-007",
        "slug": "ui-design-with-ai",
        "title": "How v0, Galileo and Figma AI changed UI design forever",
        "deck": "From blank canvas to production component in minutes — and what taste still gives you.",
        "cover": "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&q=80",
        "category": "design",
        "reading_time": 5,
        "tags": ["design", "ui", "frontend"],
        "featured": True,
        "related_tool_ids": ["v0", "galileo", "figma-ai", "framer-ai"],
        "sections": [
            _section("Generate, don't ideate",
                     "v0 produces React + Tailwind components that ship. Galileo gives you Figma-ready screens. Stop sketching, start shipping."),
            _section("Taste is the moat",
                     "AI gives every designer a head start. The differentiator is now restraint — knowing what to delete."),
        ],
    },
    {
        "id": "art-008",
        "slug": "ai-research-stack",
        "title": "How researchers actually read 200 papers a week now",
        "deck": "Perplexity, Elicit and Consensus — the trio quietly running modern literature reviews.",
        "cover": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80",
        "category": "research",
        "reading_time": 4,
        "tags": ["research", "academic"],
        "related_tool_ids": ["perplexity", "elicit", "consensus", "claude"],
        "sections": [
            _section("Cited answers in seconds",
                     "Perplexity gets you to a working bibliography before lunch."),
            _section("Deep paper extraction",
                     "Elicit reads 200M papers — filter by population, methodology, outcomes. Export structured data."),
            _section("Evidence over opinion",
                     "Consensus surfaces peer-reviewed findings on any claim. Trust, but verify."),
        ],
    },
    {
        "id": "art-009",
        "slug": "realistic-voice-ai",
        "title": "Voice AI crossed the uncanny valley — here's what we use now",
        "deck": "ElevenLabs, Suno and Descript — making real audio from text, for real productions.",
        "cover": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&q=80",
        "category": "voice",
        "reading_time": 4,
        "tags": ["voice", "audio", "music"],
        "related_tool_ids": ["elevenlabs", "suno", "descript", "udio"],
        "sections": [
            _section("Voiceovers: ElevenLabs",
                     "32+ languages, emotional control, voice cloning. The gold standard for narration and dubbing."),
            _section("Music: Suno + Udio",
                     "Full songs from a prompt. Suno is fun and fast. Udio is the producer-grade option."),
            _section("Edit: Descript",
                     "Edit audio like a Google Doc. Overdub words you fluffed. Polish like a studio."),
        ],
    },
    {
        "id": "art-010",
        "slug": "free-ai-for-beginners",
        "title": "Start here — the best free AI tools that aren't a waste of time",
        "deck": "A no-credit-card starter kit you can run today without signing your life away.",
        "cover": "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=1200&q=80",
        "category": "prompting",
        "reading_time": 3,
        "tags": ["beginner", "free"],
        "related_tool_ids": ["chatgpt", "gemini", "perplexity", "claude", "flux"],
        "sections": [
            _section("The four that matter",
                     "ChatGPT, Gemini, Claude and Perplexity — each free, each best at one thing. Learn all four; rotate based on the task."),
            _section("Images for free",
                     "Use Flux via free playgrounds. Free image gen is finally good — no excuses."),
        ],
    },
    {
        "id": "art-011",
        "slug": "ai-for-filmmaking",
        "title": "AI on set — how indie filmmakers are using Runway, Sora and Kling",
        "deck": "A practical look at three video models and what they can — and can't — actually do.",
        "cover": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80",
        "category": "video",
        "reading_time": 5,
        "tags": ["video", "filmmaking", "creator"],
        "featured": True,
        "related_tool_ids": ["runway", "sora", "kling", "midjourney"],
        "sections": [
            _section("Runway — the working horse",
                     "Used in real productions. Gen-3 is the most controllable model right now."),
            _section("Sora — the long take",
                     "Stunning continuity, surprising physics. Best for scene-level inserts."),
            _section("Kling — the affordable wildcard",
                     "Realistic, fast, generous trials. Great for storyboards and concept reels."),
        ],
    },
    {
        "id": "art-012",
        "slug": "open-source-image-models",
        "title": "Open-source image AI is good now — really good",
        "deck": "Flux, SDXL and the LoRA ecosystem make local image generation a serious craft again.",
        "cover": "https://images.unsplash.com/photo-1626544827763-d516dce335e2?w=1200&q=80",
        "category": "image-generation",
        "reading_time": 4,
        "tags": ["open-source", "image", "self-host"],
        "related_tool_ids": ["flux", "sdxl", "leonardo"],
        "sections": [
            _section("Why local matters",
                     "Privacy, cost, and freedom of style. The open ecosystem keeps closing the gap with Midjourney."),
            _section("Where to start",
                     "Flux Schnell on a cloud GPU is the fastest way in. Move to SDXL when you want to fine-tune your own style."),
        ],
    },
]


# ──────────────────────────────────────────────────────────────────
# Stacks (curated collections)
# ──────────────────────────────────────────────────────────────────
STACKS_SEED = [
    {
        "id": "stk-students", "slug": "best-ai-stack-for-students",
        "title": "Best AI stack for students",
        "persona": "Students", "use_case": "Research, writing, slides, study notes",
        "cover": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&q=80",
        "tool_ids": ["chatgpt", "perplexity", "notion-ai", "gamma", "claude"],
        "rationale": "Capture lectures, research with citations, draft essays, present beautifully. Five tools, zero overlap.",
    },
    {
        "id": "stk-creators", "slug": "best-ai-stack-for-creators",
        "title": "Best AI stack for creators",
        "persona": "Creators", "use_case": "Visuals, video, voice, publishing",
        "cover": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80",
        "tool_ids": ["midjourney", "runway", "elevenlabs", "krea", "suno"],
        "rationale": "Concept, shoot, edit and score — a complete creative pipeline.",
    },
    {
        "id": "stk-founders", "slug": "best-ai-stack-for-founders",
        "title": "Best AI stack for founders",
        "persona": "Founders", "use_case": "Build, ship, market and automate",
        "cover": "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80",
        "tool_ids": ["v0", "cursor", "zapier-ai", "gamma", "perplexity"],
        "rationale": "Prototype products, automate ops, research markets, pitch the round.",
    },
    {
        "id": "stk-designers", "slug": "best-ai-stack-for-designers",
        "title": "Best AI stack for designers",
        "persona": "Designers", "use_case": "Concepting, UI, brand & visuals",
        "cover": "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=1200&q=80",
        "tool_ids": ["figma-ai", "v0", "galileo", "midjourney", "magnific"],
        "rationale": "Generate UI, refine in Figma, polish to print quality — taste-first workflow.",
    },
    {
        "id": "stk-researchers", "slug": "best-ai-stack-for-researchers",
        "title": "Best AI stack for researchers",
        "persona": "Researchers", "use_case": "Literature, synthesis, writing",
        "cover": "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=1200&q=80",
        "tool_ids": ["perplexity", "elicit", "consensus", "claude", "notion-ai"],
        "rationale": "From discovery to draft — peer-reviewed evidence at every step.",
    },
    {
        "id": "stk-developers", "slug": "best-ai-stack-for-developers",
        "title": "Best AI stack for developers",
        "persona": "Developers", "use_case": "Ship code, faster",
        "cover": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80",
        "tool_ids": ["cursor", "github-copilot", "v0", "claude", "bolt"],
        "rationale": "Pair-programming, UI generation, code review, and rapid prototyping in one stack.",
    },
]
